steps:
- id: 'Build Image'
  name: 'gcr.io/cloud-builders/docker'
  args: ["build", "-t", "gcr.io/${PROJECT_ID}/hello:${SHORT_SHA}", "."]
- id: 'Push Image'
  name: 'gcr.io/cloud-builders/docker'
  args: ["push", "gcr.io/${PROJECT_ID}/hello:${SHORT_SHA}"]
- id: 'Deploy to Cloud Run'
  name: 'gcr.io/cloud-builders/gcloud'
  args: ['beta', 'run', 'deploy', 'hello', '--image', 'gcr.io/${PROJECT_ID}/hello:${SHORT_SHA}', '--allow-unauthenticated', '--region', 'us-central1','--platform', 'managed']
images:
- "gcr.io/${PROJECT_ID}/hello:${SHORT_SHA}"